use ry;
DROP TABLE IF EXISTS `ddpayorder`;
CREATE TABLE `ddpayorder` (
                              `id` int NOT NULL AUTO_INCREMENT COMMENT '编号',
                              `appid` varchar(512) DEFAULT NULL COMMENT '店铺编号',
                              `name` varchar(512) DEFAULT NULL COMMENT '店铺名称',
                              `orderId` varchar(512) DEFAULT NULL COMMENT '单号',
                              `phone` varchar(100) DEFAULT NULL COMMENT '手机号',
                              `amount` decimal(10,0) DEFAULT NULL COMMENT '金额',
                              `orderUrl` varchar(2048) DEFAULT NULL COMMENT '下单地址',
                              `payUrl` varchar(2048) DEFAULT NULL COMMENT '支付地址',
                              `method` varchar(100) DEFAULT NULL COMMENT '付款方式',
                              `cookie` varchar(2048) DEFAULT NULL COMMENT 'cookie',
                              `body` varchar(2048) DEFAULT NULL COMMENT 'body',
                              `response` longtext CHARACTER SET utf8mb4  COMMENT '返回内容',
                              `result` longtext CHARACTER SET utf8mb4  COMMENT '结果',
                              `invalidTime` datetime DEFAULT NULL COMMENT '失效时间',
                              `status` int NOT NULL DEFAULT '0' COMMENT '支付状态',
                              `callbackUrl` varchar(255) DEFAULT NULL COMMENT '回调地址',
                              `callbackStatus` int DEFAULT NULL,
                              `merchantOrderNo` varchar(255) CHARACTER SET utf8mb4  DEFAULT NULL,
                              `completionTime` datetime DEFAULT NULL COMMENT '完成时间',
                              `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除,0否,1是',
                              `createTime` datetime NOT NULL COMMENT '创建时间',
                              `updateTime` datetime DEFAULT NULL COMMENT '修改时间',
                              `createBy` varchar(100) DEFAULT NULL COMMENT '创建人',
                              `updateBy` varchar(100) DEFAULT NULL COMMENT '最后修改人',
                              `createId` int DEFAULT NULL COMMENT '创建人ID',
                              `updateId` int DEFAULT NULL COMMENT '最后修改人ID',
                              PRIMARY KEY (`id`),
                              KEY `ddPayOrder_orderId_IDX` (`orderId`) USING BTREE,
                              KEY `ddPayOrder_completionTime_IDX` (`completionTime`) USING BTREE,
                              KEY `ddPayOrder_createTime_IDX` (`createTime`) USING BTREE,
                              KEY `ddPayOrder_status_IDX` (`status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=376 DEFAULT CHARSET=utf8mb4  COMMENT='多多373订单表';

DROP TABLE IF EXISTS `ddpayshop`;
CREATE TABLE `ddpayshop` (
                             `id` int NOT NULL AUTO_INCREMENT COMMENT '编号',
                             `name` varchar(512) DEFAULT NULL COMMENT '店铺名称',
                             `appid` varchar(512) DEFAULT NULL COMMENT 'appid',
                             `clientid` varchar(512) DEFAULT NULL COMMENT 'clientid',
                             `clientsec` varchar(512) DEFAULT NULL COMMENT 'clientsec',
                             `msg_token` varchar(512) DEFAULT NULL COMMENT 'msg_token',
                             `cookie` varchar(2048) DEFAULT NULL COMMENT 'cookie',
                             `key` varchar(512) DEFAULT NULL COMMENT 'key',
                             `pushUrl` varchar(1024) DEFAULT NULL COMMENT '推送地址',
                             `payMethod` varchar(100) DEFAULT NULL COMMENT '收款方式',
                             `cookieExpire` int DEFAULT NULL COMMENT 'cookie有效时长（秒）',
                             `cookieCount` int DEFAULT NULL COMMENT 'cookie启动个数（0任务停止）',
                             `cookieMaxOrder` int DEFAULT NULL COMMENT 'cookie最大订单数（0不限制）',
                             `status` bit(1) NOT NULL DEFAULT b'0' COMMENT '状态',
                             `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
                             `createTime` datetime NOT NULL COMMENT '创建时间',
                             `updateTime` datetime DEFAULT NULL COMMENT '修改时间',
                             `createBy` varchar(100) DEFAULT NULL COMMENT '创建人',
                             `updateBy` varchar(100) DEFAULT NULL COMMENT '最后修改人',
                             `createId` int DEFAULT NULL COMMENT '创建人ID',
                             `updateId` int DEFAULT NULL COMMENT '最后修改人ID',
                             PRIMARY KEY (`id`),
                             KEY `ddPayShop_name_IDX` (`name`) USING BTREE,
                             KEY `ddPayShop_appid_IDX` (`appid`) USING BTREE,
                             KEY `ddPayShop_createTime_IDX` (`createTime`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4  COMMENT='多多373店铺表';
